---
- name: Install automatic upgrades packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - unattended-upgrades
    - update-notifier-common

- name: Enable automatic updates
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: files/20auto-upgrades
      dest: /etc/apt/apt.conf.d/20auto-upgrades
    - src: files/50unattended-upgrades
      dest: /etc/apt/apt.conf.d/50unattended-upgrades
