---
- name: Install fail2ban
  package:
    name: fail2ban
    state: latest
  notify:
    - restart fail2ban

- name: Install sshd
  package:
    name: openssh-server
    state: latest

- name: Lock down SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: '^PermitRootLogin'
      line: 'PermitRootLogin no'
    - regexp: '^PasswordAuthentication'
      line: 'PasswordAuthentication no'
    - regexp: '^AllowUsers'
      line: 'AllowUsers {{ base__provisioning_username }} {{ base__operator_username }}'
  notify:
    - restart sshd

- name: Install firewall
  package:
    name: ufw
    state: latest
  notify:
    - close all ports
