---
- name: Install tzdata
  package:
    name: tzdata
    state: present

- name: Update timezone
  timezone:
    name: "{{ base__timezone }}"

- name: Install ntpd
  package:
    name: ntp
    state: present

- name: Configure ntpd
  copy:
    src: files/ntp.conf
    dest: /etc/ntp.conf
  notify:
    - restart ntpd
