---
- name: Install tzdata
  ansible.builtin.package:
    name: tzdata
    state: present

- name: Update timezone
  timezone:
    name: "{{ base__timezone }}"

- name: Configure network time servers
  ansible.builtin.template:
    src: templates/timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: 0o644
