---
- name: Enable passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^{{ item }}\s'
    line: '{{ item }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  with_items:
    - "{{ base__provisioning_username }}"
    - "{{ base__operator_username }}"

- name: Create users and disable passwords
  user:
    name: "{{ item }}"
    password: "!!"
    state: present
  with_items:
    - root
    - "{{ base__provisioning_username }}"
    - "{{ base__operator_username }}"

- name: Set a password for operator account
  user:
    name: "{{ base__operator_username }}"
    password:
    state: present

- name: Add public keys
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', base__ssh_pubkey_path) }}"
  with_items:
    - "{{ base__provisioning_username }}"
    - "{{ base__operator_username }}"

