---
- name: Enable passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^{{ item }}\s'
    line: "{{ item }} ALL=(ALL) NOPASSWD:ALL"
    validate: "visudo -cf %s"
  with_items:
    - "{{ base__provisioning_username }}"
    - "{{ base__operator_username }}"

- name: Create users and disable passwords  # noqa no-log-password
  user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    state: present
  with_items:
    - username: root
      password: "!!"
    - username: "{{ base__operator_username }}"
      password: "{{ base__operator_password }}"
      shell: "{{ base__operator_shell }}"
    - username: "{{ base__provisioning_username }}"
      password: "!!"

- name: Add public keys
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', base__ssh_pubkey_path) }}"
  with_items:
    - "{{ base__provisioning_username }}"
    - "{{ base__operator_username }}"
