---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Destroy molecule instance(s)
      lxd_container:
        name: "{{ item.name }}"
        state: absent
        force_stop: "{{ item.force_stop | default(true) }}"
      with_items: "{{ molecule_yml.platforms }}"
