---
dependency:
  name: galaxy
driver:
  name: lxd
lint: yamllint
platforms:
  - name: ubuntu-bionic
    alias: ubuntu/bionic
  - name: ubuntu-xenial
    alias: ubuntu/xenial

provisioner:
  name: ansible
  playbooks:
    create: ../create.yml
    destroy: ../destroy.yml
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
