---
dependency:
  name: galaxy
driver:
  name: lxd
lint: |
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ubuntu-focal
    alias: ubuntu/focal
  - name: ubuntu-bionic
    alias: ubuntu/bionic
  - name: ubuntu-xenial
    alias: ubuntu/xenial

provisioner:
  name: ansible
  playbooks:
    create: ../create.yml
    destroy: ../destroy.yml
scenario:
  name: default
verifier:
  name: testinfra
