---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ubuntu1804
    image: geerlingguy/docker-ubuntu1804-ansible
    alias: ubuntu/bionic
  - name: ubuntu2004
    image: geerlingguy/docker-ubuntu2004-ansible
    alias: ubuntu/focal

provisioner:
  name: ansible
  playbooks:
    create: ../create.yml
    destroy: ../destroy.yml
scenario:
  name: default
verifier:
  name: testinfra
