---
dependency:
  name: galaxy
driver:
  name: lxd
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ubuntu-2004-focal
    alias: ubuntu/focal
  - name: ubuntu-1804-bionic
    alias: ubuntu/bionic
  - name: ubuntu-1604-xenial
    alias: ubuntu/xenial

provisioner:
  name: ansible
  playbooks:
    create: ../create.yml
    destroy: ../destroy.yml
scenario:
  name: default
verifier:
  name: testinfra
