---
'on':
  pull_request:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: |
          pip3 install yamllint==1.26.1 ansible-lint==6.0.2 flake8==3.9.2

      - name: Lint code
        run: |
          molecule lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Install LXD
        uses: whywaita/setup-lxd@v1
        with:
          lxd_version: latest/stable

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: >-
          pip3 install 
            ansible==5.6.0
            ansible-lint==6.0.2
            flake8==3.9.2
            yamllint==1.26.1
            molecule==3.6.1
            molecule-lxd
            pytest-testinfra==6.4.0

      - name: Run molecule
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
