---
on: push

jobs:
  molecule:
    runs-on:
      - unbuntu-20.04
      - unbuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - uses: gofrolist/molecule-action@v2
