---
'on':
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: whywaita/setup-lxd@v1
        with:
          lxd_version: latest/stable
      - uses: BSFishy/pip-action@v1
        with:
          # ansible 5.6.0 is really 2.12.4
          packages: |
            ansible==5.6.0
            ansible-lint==6.0.2
            flake8==3.9.2
            yamllint==1.26.1
            molecule==3.6.1
            molecule-lxd
            pytest-testinfra==6.4.0
      - name: Run molecule
        run: molecule test
        end:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
  release:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: galaxy
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: https://galaxy.ansible.com/api/v1/notifications/
          webhook_secret: ${{ secrets.galaxy_api_key }}
